### ISSUE TITLE
wan 口不能正常启动

### ISSUE THREAD

**Issue by 2324059** [lixuande/rt2860v2-detect#1]
[   20.310000]  RX BW Filter Calibration !!!
[   20.540000] LOFT Calibration Done!
[   20.550000] IQCalibration Start!
[   20.570000] IQCalibration Done! CH = 0, (gain= f, phase= 0)
[   20.580000] IQCalibration Start!
[   20.600000] IQCalibration Done! CH = 1, (gain= 1, phase=3d)
[   20.610000] TX IQ Calibration Done!
[   20.650000] MCS Set = ff ff 00 00 01
[   20.690000] SYNC - BBP R4 to 20MHz.l
[   22.930000] Main bssid = 78:a3:51:08:14:60
[   22.940000] <==== rt28xx_init, Status=0
[   22.950000] 0x1300 = 00064380
[   23.030000] 8021q: adding VLAN 0 to HW filter on device eth0
[   23.090000] device eth0.1 entered promiscuous mode
[   23.100000] device eth0 entered promiscuous mode
[   23.150000] br-lan: port 1(eth0.1) entered forwarding state
[   23.160000] br-lan: port 1(eth0.1) entered forwarding state
[   24.200000] ralink_soc_eth 10100000.ethernet eth0: port 4 link up (10Mbps/Half duplex)
[   24.220000] ralink_soc_eth 10100000.ethernet eth0: port 5 link up (10Mbps/Half duplex)
[   25.160000] br-lan: port 1(eth0.1) entered forwarding state
[   26.220000] device ra0 entered promiscuous mode
[   26.230000] br-lan: port 2(ra0) entered forwarding state
[   26.240000] br-lan: port 2(ra0) entered forwarding state

lan口都正常了，wan口没起来？？？
7620a的片子 ，问问什么问题，怎么解决。

**Comment by lixuande** [comment]
看样子是社区的驱动。
看一下/etc/config/network和target下02_network的配置是否有问题

**Comment by 2324059** [comment]
谢谢，
